meta_product_name: "Bottle Trends"
meta_title: "Bottle Trends - Faites de votre vin un investissement financier"
meta_description: "De plus en plus de personnes souhaitent investir dans le vin pour le collectionner ou le revendre, mais ne savent pas comment investir. Bottle Trends est une plateforme d'investissement permettant de voir les tendances de vos bouteilles, de gérer votre collection / portefeuille, et de revendre vos possessions avec une plus value."
meta_image: "cover.png" # should exist in `app/assets/images/`
